
// hardcoded moods data and corresponding pixabay query
export const MOODS = {
  OVERJOYED: {
    id: "overjoyed",
    label: "Overjoyed",
    emoji: "🤗",
    score: 10,
    color: "yellow",
    prompt: "What filled your day with pure joy and excitement?",
    pixabayQuery: "happy+joy+celebration+people+smiling",
  },
  ACCOMPLISHED: {
    id: "accomplished",
    label: "Accomplished",
    emoji: "⭐",
    score: 9,
    color: "amber",
    prompt: "What goals or tasks did you successfully complete?",
    pixabayQuery: "success+achievement+winner+trophy",
  },
  INSPIRED: {
    id: "inspired",
    label: "Inspired",
    emoji: "💫",
    score: 9,
    color: "violet",
    prompt: "What idea or moment sparked your inspiration today?",
    pixabayQuery: "creative+inspiration+lightbulb+sky",
  },
  PROUD: {
    id: "proud",
    label: "Proud",
    emoji: "🦁",
    score: 9,
    color: "amber",
    prompt: "What accomplishment made you feel proud today?",
    pixabayQuery: "proud+achievement+victory+strong",
  },
  LOVED: {
    id: "loved",
    label: "Loved",
    emoji: "🥰",
    score: 9,
    color: "pink",
    prompt: "Who made you feel truly loved and cared for?",
    pixabayQuery: "love+affection+couple+heart",
  },
  APPRECIATED: {
    id: "appreciated",
    label: "Appreciated",
    emoji: "💝",
    score: 8,
    color: "rose",
    prompt: "How did someone show gratitude or appreciation for you?",
    pixabayQuery: "gratitude+thankful+smile+kindness",
  },
  MOTIVATED: {
    id: "motivated",
    label: "Motivated",
    emoji: "🎯",
    score: 8,
    color: "emerald",
    prompt: "What's pushing you to keep moving forward today?",
    pixabayQuery: "motivation+goal+determination+focus",
  },
  HAPPY: {
    id: "happy",
    label: "Happy",
    emoji: "😊",
    score: 8,
    color: "amber",
    prompt: "What made you feel light-hearted and cheerful today?",
    pixabayQuery: "happy+smile+sun+joy",
  },
  EXCITED: {
    id: "excited",
    label: "Excited",
    emoji: "🎉",
    score: 8,
    color: "orange",
    prompt: "What event or moment are you looking forward to?",
    pixabayQuery: "excited+celebration+fun+fireworks",
  },
  CONFIDENT: {
    id: "confident",
    label: "Confident",
    emoji: "💪",
    score: 8,
    color: "emerald",
    prompt: "What made you feel strong and self-assured today?",
    pixabayQuery: "confidence+success+strength+power",
  },
  GRATEFUL: {
    id: "grateful",
    label: "Grateful",
    emoji: "🙏",
    score: 8,
    color: "green",
    prompt: "What made you pause and feel thankful today?",
    pixabayQuery: "gratitude+thankful+peaceful+hands",
  },
  CONNECTED: {
    id: "connected",
    label: "Connected",
    emoji: "🤝",
    score: 8,
    color: "indigo",
    prompt: "Who did you feel deeply connected to today?",
    pixabayQuery: "connection+community+friends+teamwork",
  },
  PEACEFUL: {
    id: "peaceful",
    label: "Peaceful",
    emoji: "😌",
    score: 7,
    color: "blue",
    prompt: "What moment brought you stillness and calm?",
    pixabayQuery: "peaceful+serene+calm+nature+relax",
  },
  HOPEFUL: {
    id: "hopeful",
    label: "Hopeful",
    emoji: "🌱",
    score: 7,
    color: "green",
    prompt: "What gave you a sense of hope today?",
    pixabayQuery: "hope+light+growth+future",
  },
  CREATIVE: {
    id: "creative",
    label: "Creative",
    emoji: "🎨",
    score: 7,
    color: "violet",
    prompt: "What did you make or imagine that felt creative?",
    pixabayQuery: "art+creativity+design+colors+paint",
  },
  THOUGHTFUL: {
    id: "thoughtful",
    label: "Thoughtful",
    emoji: "🤔",
    score: 6,
    color: "slate",
    prompt: "What have you been deeply reflecting on?",
    pixabayQuery: "thinking+reflection+quiet+mindful",
  },
  CURIOUS: {
    id: "curious",
    label: "Curious",
    emoji: "🧐",
    score: 6,
    color: "teal",
    prompt: "What sparked your curiosity today?",
    pixabayQuery: "curious+explore+discovery+learning",
  },
  NOSTALGIC: {
    id: "nostalgic",
    label: "Nostalgic",
    emoji: "🌅",
    score: 5,
    color: "fuchsia",
    prompt: "What old memory are you revisiting?",
    pixabayQuery: "nostalgia+memories+vintage+sunset",
  },
  NEUTRAL: {
    id: "neutral",
    label: "Neutral",
    emoji: "😐",
    score: 5,
    color: "gray",
    prompt: "How did your day unfold, moment to moment?",
    pixabayQuery: "neutral+balance+calm+ordinary",
  },
  RESTLESS: {
    id: "restless",
    label: "Restless",
    emoji: "🌊",
    score: 4,
    color: "blue",
    prompt: "What’s keeping you on edge or uneasy?",
    pixabayQuery: "restless+motion+waves+energy",
  },
  TIRED: {
    id: "tired",
    label: "Tired",
    emoji: "😴",
    score: 4,
    color: "purple",
    prompt: "What has been draining your energy?",
    pixabayQuery: "tired+sleep+rest+fatigue",
  },
  OVERWHELMED: {
    id: "overwhelmed",
    label: "Overwhelmed",
    emoji: "😵",
    score: 3,
    color: "sky",
    prompt: "What responsibilities are weighing you down?",
    pixabayQuery: "overwhelmed+chaos+stress+storm",
  },
  ANXIOUS: {
    id: "anxious",
    label: "Anxious",
    emoji: "😰",
    score: 3,
    color: "indigo",
    prompt: "What’s been causing you to feel uneasy or nervous?",
    pixabayQuery: "anxiety+worry+stress+nervous",
  },
  DISAPPOINTED: {
    id: "disappointed",
    label: "Disappointed",
    emoji: "😞",
    score: 3,
    color: "stone",
    prompt: "What didn’t go the way you had hoped?",
    pixabayQuery: "disappointment+failure+cloudy+sad",
  },
  FRUSTRATED: {
    id: "frustrated",
    label: "Frustrated",
    emoji: "😤",
    score: 3,
    color: "orange",
    prompt: "What obstacles are testing your patience?",
    pixabayQuery: "frustrated+blocked+problem+barrier",
  },
  STRESSED: {
    id: "stressed",
    label: "Stressed",
    emoji: "😫",
    score: 3,
    color: "rose",
    prompt: "What pressure or demands are stressing you out?",
    pixabayQuery: "stress+pressure+busy+overwhelmed",
  },
  INSECURE: {
    id: "insecure",
    label: "Insecure",
    emoji: "🥺",
    score: 2,
    color: "lime",
    prompt: "What made you feel uncertain or unsure of yourself?",
    pixabayQuery: "insecure+doubt+uncertainty+alone",
  },
  SAD: {
    id: "sad",
    label: "Sad",
    emoji: "😢",
    score: 2,
    color: "cyan",
    prompt: "What’s been weighing on your heart today?",
    pixabayQuery: "sad+tears+rain+lonely",
  },
  LONELY: {
    id: "lonely",
    label: "Lonely",
    emoji: "🌙",
    score: 2,
    color: "zinc",
    prompt: "What could help you feel more connected?",
    pixabayQuery: "lonely+solitude+night+alone",
  },
  ANGRY: {
    id: "angry",
    label: "Angry",
    emoji: "😠",
    score: 1,
    color: "red",
    prompt: "What sparked your anger or frustration today?",
    pixabayQuery: "angry+rage+storm+fire",
  },
};

export function getMoodById(moodId){
    return MOODS[moodId?.toUpperCase()]
}

export function getMoodTrend(averageScore) {
  if (averageScore >= 9) return "You've been unstoppable!";
  if (averageScore >= 8) return "You've been feeling great!";
  if (averageScore >= 6) return "You've been doing well overall.";
  if (averageScore >= 4) return "You've been feeling okay.";
  if (averageScore >= 2) return "Things have been challenging.";
  return "You've been having a tough time.";
};